src/Entity/Area.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AreaRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: AreaRepository::class)]
class Area
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, unique: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $detail = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column]
    private ?int $nbRooms = null;

    #[ORM\Column(length: 30)]
    private ?string $type = null;

    #[ORM\Column(length: 30)]
    private ?string $status = null;

    #[ORM\OneToMany(mappedBy: 'area', targetEntity: ExpositionProposal::class)]
    private Collection $expositionProposals;

    #[ORM\OneToMany(mappedBy: 'area', targetEntity: AreaParticipation::class)]
    private Collection $areaParticipations;

    #[ORM\ManyToMany(targetEntity: AreaCategory::class, inversedBy: 'areas')]
    private Collection $areaCategories;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $quote = null;

    #[ORM\OneToMany(mappedBy: 'area', targetEntity: Picture::class, cascade: ['remove'])]
    private Collection $pictures;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $access = null;



    public function __construct()
    {
        $this->expositionProposals = new ArrayCollection();
        $this->areaParticipations = new ArrayCollection();
        $this->areaCategories = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getFormattedStartDate(): ?string
    {
        return $this->startDate ? $this->startDate->format('d.m.Y') : null;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getNbRooms(): ?int
    {
        return $this->nbRooms;
    }

    public function setNbRooms(int $nbRooms): static
    {
        $this->nbRooms = $nbRooms;

        return $this;
    }

    public function getNbReversationMade() {
        return count($this->areaParticipations);
    }

    public function getNbReversationRemaining() {
        return $this->nbRooms - count($this->areaParticipations);
    }


    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, ExpositionProposal>
     */
    public function getExpositionProposals(): Collection
    {
        return $this->expositionProposals;
    }

    public function addExpositionProposal(ExpositionProposal $expositionProposal): static
    {
        if (!$this->expositionProposals->contains($expositionProposal)) {
            $this->expositionProposals->add($expositionProposal);
            $expositionProposal->setArea($this);
        }

        return $this;
    }

    public function removeExpositionProposal(ExpositionProposal $expositionProposal): static
    {
        if ($this->expositionProposals->removeElement($expositionProposal)) {
            // set the owning side to null (unless already changed)
            if ($expositionProposal->getArea() === $this) {
                $expositionProposal->setArea(null);
            }
        }

        return $this;
    }

    public function getNbExpositionProposals() 
    {
        return count($this->expositionProposals);
    }

    

    /**
     * @return Collection<int, AreaParticipation>
     */
    public function getAreaParticipations(): Collection
    {
        return $this->areaParticipations;
    }

    public function addAreaParticipation(AreaParticipation $areaParticipation): static
    {
        if (!$this->areaParticipations->contains($areaParticipation)) {
            $this->areaParticipations->add($areaParticipation);
            $areaParticipation->setArea($this);
        }

        return $this;
    }

    public function removeAreaParticipation(AreaParticipation $areaParticipation): static
    {
        if ($this->areaParticipations->removeElement($areaParticipation)) {
            // set the owning side to null (unless already changed)
            if ($areaParticipation->getArea() === $this) {
                $areaParticipation->setArea(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, AreaCategory>
     */
    public function getAreaCategories(): Collection
    {
        return $this->areaCategories;
    }

    public function addAreaCategory(AreaCategory $areaCategory): static
    {
        if (!$this->areaCategories->contains($areaCategory)) {
            $this->areaCategories->add($areaCategory);
        }

        return $this;
    }

    public function removeAreaCategory(AreaCategory $areaCategory): static
    {
        $this->areaCategories->removeElement($areaCategory);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function generateSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->getName());
    }

    public function getQuote(): ?string
    {
        return $this->quote;
    }

    public function setQuote(?string $quote): static
    {
        $this->quote = $quote;

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): static
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setArea($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): static
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getArea() === $this) {
                $picture->setArea(null);
            }
        }

        return $this;
    }

    public function getAccess(): ?string
    {
        return $this->access;
    }

    public function setAccess(?string $access): static
    {
        $this->access = $access;

        return $this;
    }

   
}

src/Entity/Studio.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\StudioRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: StudioRepository::class)]
class Studio
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $detail = null;

    #[ORM\Column]
    private ?int $nbRooms = null;

    #[ORM\OneToMany(mappedBy: 'studio', targetEntity: Timeslot::class)]
    private Collection $timeslots;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(nullable: true)]
    private ?array $equipment = null;

    #[ORM\OneToMany(mappedBy: 'studio', targetEntity: Picture::class)]
    private Collection $pictures;

    public function __toString() 
    {
        return $this->name; 
    }

    public function __construct()
    {
        $this->timeslots = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getNbRooms(): ?int
    {
        return $this->nbRooms;
    }

    public function setNbRooms(int $nbRooms): static
    {
        $this->nbRooms = $nbRooms;

        return $this;
    }

    public function getNbRegistrationMade()
    {
        return count($this->timeslots);
    }

    public function getNbRegistrationRemaining() 
    {
        return $this->nbRooms - count($this->timeslots);
    }

    /**
     * @return Collection<int, Timeslot>
     */
    public function getTimeslots(): Collection
    {
        return $this->timeslots;
    }

    public function addTimeslot(Timeslot $timeslot): static
    {
        if (!$this->timeslots->contains($timeslot)) {
            $this->timeslots->add($timeslot);
            $timeslot->setStudio($this);
        }

        return $this;
    }

    public function removeTimeslot(Timeslot $timeslot): static
    {
        if ($this->timeslots->removeElement($timeslot)) {
            // set the owning side to null (unless already changed)
            if ($timeslot->getStudio() === $this) {
                $timeslot->setStudio(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function generateSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->getName());
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getEquipment(): ?array
    {
        return $this->equipment;
    }

    public function setEquipment(?array $equipment): static
    {
        $this->equipment = $equipment;

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): static
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setStudio($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): static
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getStudio() === $this) {
                $picture->setStudio(null);
            }
        }

        return $this;
    }
}

templates/dashboard/indexStudios.html.twig
{% extends 'base.html.twig' %}

{% block title %}Expositions list - MOSAIC{% endblock %}
{% block meta %}{% endblock %}

{% block body %}


<section class="dashboard" id="dashboard-events">

    <div id="menu-left">
        <div id="logo-name">
            <figure>
               <img src="{{ asset('images/logo150.png')}}" alt="logo of the website"> 
            </figure>      
            <p class="text-n1">MOSAIC</p>
        </div>

        <div class="separator-line"></div>

        <div id="list-menu">
            <a href="{{ path('app_dashboard') }}"><div><i class="ri-dashboard-fill"></i><p>dashboard</p></div></a>
            <a href="{{ path('list_users') }}"> <div ><i class="ri-team-fill "></i><p>Community</p></div></a>
            <a href="{{ path('list_events') }}"> <div ><i class="ri-artboard-2-fill"></i><p>events</p> </div></a>
            <a href="{{ path('list_expos') }}"><div><i class="ri-artboard-fill"></i><p>expositions</p> </div></a>
            <a href="{{ path('list_workshops') }}"><div><i class="ri-palette-fill"></i><p>workshops</p> </div></a>
            <a href="{{ path('list_studios') }}"><div  class="is-active"><i class="ri-home-heart-fill"></i><p>studios</p> </div></a>
            {# <div><i class="ri-calendar-fill"></i><p>calendar</p></div>
            <div><i class="ri-calendar-schedule-fill"></i><p>planning</p></div> #}
        </div>

        <div id="bottom"></div>

    </div>

    <div id="content">

        <div id="top-title">
            <p class="text-n1">Studios<span>_</span></p>
            <div class="separator-line"></div>
        </div>

        <div id="action-create">
            {# <p><a class="btn btn6" href="{{ path('new_expo') }}"> NEW EXPOSITION</a></p> #}
       </div>


        <div class="container-all dashboard-studios">
                
            <div id="studios">
                <div class="ongoing">
                    {% for studio in studios %}
                    <div class="element">
                        <div>
                            <a href="{{ path('show_studio_admin', {slug : studio.slug}) }}"><span class="name text-n2">✦ {{studio.name}}</span></a>
                        
                        <button class="btn btn6"><a href="{{ path('edit_studio', {slug : studio.slug}) }}">EDIT</a></button></div>
                        <p>Capacity: {{studio.nbRooms}} </p>
                    </div>
                    <hr>
                    {% endfor %}
                </div>
    
            </div>

    
        </div>

        
    </div>

    
</section>



{% endblock %}

templates/dashboard/showEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block meta %}{% endblock %}

{% block body %}




<section id="dashboard-show">

    <div id="link-goBack" >
        <p><a href="{{ path('list_events') }}">Go back to all Events</a> <p>
    </div>

        <h1 class="text-n1">{{area.name}}<span>_</span></h1>
        <div id="info">
            <p>Status : 
                <span class="status {{ area.status == 'OPEN' ? 'open' : 
                                    (area.status == 'CLOSED' ? 'closed' : 
                                    (area.status == 'PENDING' ? 'pending' : 
                                    (area.status == 'ARCHIVED' ? 'archived' : 'status-default'))) }}">
                    {{ area.status }}
                </span>
            </p>
            <p>Access: {{ area.access }}</p>
            <p>Date :  {{area.startDate|formatDate}} - {{area.startDate|date('H:i')}} </p>
            <p>Capacity : {{area.nbReversationMade}}  /  {{area.nbRooms}} - Remaining : {{area.nbReversationRemaining}} </p>

            <div class="text">
                <p>Description : </p>
                <p>{{area.description}}</p>
            </div>
            <div class="text">
                <p>Detail : </p>
                <p>{{area.detail}}</p>
            </div>
            
            <p>Quote : {{area.quote}}</p>

            <div id="actions">
                <a href="{{ path('edit_event', {'id' : area.id}) }}"><i class="fa-solid fa-pen-to-square"></i>edit</a>
                <a href="#"><i class="fa-regular fa-circle-xmark delete-trigger2"></i>delete</a>
            </div>
            
            <div class="delete-container2" style="display:none">
                <p>Are you sure you want to delete this entry? This cannot be undone.</p>
                <div>
                    <p><a href="{{ path('delete_event', {slug : area.slug}) }}"><i class="ri-check-line"></i> Confirm</a></p>
                    <p class="close-confirmation-btn2"><i class="ri-close-fill "></i> Cancel</p>
                </div>
            </div>


        </div>
        

        <h2 class="text-n2" >Participants list<span>_</span></h2>
        
        <div id="participants">
            <ul>
                {% for participant in area.areaParticipations %}
                    <li>
                        <p>
                            {{ participant.firstname}} - {{ participant.lastname}} -  {{ participant.inscriptionDate|formatDate}} 
                            <a href="#"><i class="ri-close-circle-fill delete-btn" data-target="{{ participant.id}}"></i></a>
                        </p>
                        
                        <div class="delete-container" id="{{participant.id}}" style="display:none">
                            <p>Are you sure you want to delete this participation? This cannot be undone.</p>
                            <div>
                                <p><a href="{{ path('delete_participation', {'id': participant.id }) }}"><i class="ri-check-line"></i> Confirm</a></p>
                                <p class="close-confirmation-btn"><i class="ri-close-fill "></i> Cancel</p>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>


<script>
    $(document).ready(function() {

        $('.delete-trigger2').click(function() {
            event.preventDefault();
            $('.delete-container2').slideToggle();
        });
    
        $('.close-confirmation-btn2').click(function() {
            $('.delete-container2').slideToggle();
        });
    });
</script>
{% endblock %}

templates/dashboard/showExpo.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block meta %}{% endblock %}

{% block body %}



<section id="dashboard-show">

    <div id="link-goBack" >
        <p><a href="{{ path('list_expos') }}">Go back to all Expositions</a> <p>
    </div>


    <h1 class="text-n1">{{area.name}}<span>_</span></h1>
    <div id="info">
        <p>Status : 
            <span class="status {{ area.status == 'OPEN' ? 'open' : 
                                (area.status == 'CLOSED' ? 'closed' : 
                                (area.status == 'PENDING' ? 'pending' : 
                                (area.status == 'ARCHIVED' ? 'archived' : 'status-default'))) }}">
                {{ area.status }}
            </span>
        </p>
        <p>Date :  {{area.startDate|formatDate}} - {{area.startDate|date('H:i')}} /  {{area.endDate|formatDate}} - {{area.endDate|date('H:i')}}  </p>
        <p>Capacity : {{area.nbReversationMade}}  /  {{area.nbRooms}} - Remaining : {{area.nbReversationRemaining}} </p>

        <div class="text">
            <p>Description : </p>
            <p>{{area.description}}</p>
        </div>
        <div class="text">
            <p>Detail : </p>
            <p>{{area.detail}}</p>
        </div>
        
        <p>Quote : {{area.quote}}</p>

        <div id="actions">
            <a href="{{ path('edit_expo', {'id' : area.id}) }}"><i class="fa-solid fa-pen-to-square"></i>edit</a>
            <a href="#"><i class="fa-regular fa-circle-xmark delete-trigger2"></i>delete</a>
        </div>
        
        <div class="delete-container2" style="display:none">
            <p>Are you sure you want to delete this entry? This cannot be undone.</p>
            <div>
                <p><a href="{{ path('delete_expo', {slug : area.slug}) }}"><i class="ri-check-line"></i> Confirm</a></p>
                <p class="close-confirmation-btn2"><i class="ri-close-fill "></i> Cancel</p>
            </div>
        </div>
    </div>

    <div id="participants">
        <h2 class="text-n2" >Participants list<span>_</span></h2>
        <ul>
            {% for participant in area.areaParticipations %}
                <li>
                    <p>
                        {{ participant.firstname}} - {{ participant.lastname}} -  {{ participant.inscriptionDate|formatDate}} 
                        <a href="#"><i class="ri-close-circle-fill delete-btn" data-target="{{ participant.id}}"></i></a>
                    </p>
                    
                    <div class="delete-container" id="{{participant.id}}" style="display:none">
                        <p>Are you sure you want to delete this participation? This cannot be undone.</p>
                        <div>
                            <p><a href="{{ path('delete_participation', {'id': participant.id }) }}"><i class="ri-check-line"></i> Confirm</a></p>
                            <p class="close-confirmation-btn"><i class="ri-close-fill "></i> Cancel</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div id="participants">
        <h2 class="text-n2" >Artists list<span>_</span></h2>
    </div>
    {% if area.expositionProposals is not empty%}
        <ul>
            {% for proposal in area.expositionProposals %}
                <li>
                    <p>
                        <a href="{{ path('show_artist', {slug: proposal.user.slug}) }}"> {{ proposal.user.artistInfos.artistName }} </a>
                       - {{ proposal.user.artistInfos.discipline }} - {{ proposal.user.artistInfos.emailPro}}
                        <a href="#"><i class="ri-close-circle-fill delete-btn" data-target="{{ proposal.id}}"></i></a>
                    </p>
                    
                    <div class="delete-container" id="{{proposal.id}}" style="display:none">
                        <p>Are you sure you want to delete this artist proposal? This cannot be undone.</p>
                        <div>
                            <p><a href="{{ path('delete_proposal', {'id': proposal.id }) }}"><i class="ri-check-line"></i> Confirm</a></p>
                            <p class="close-confirmation-btn"><i class="ri-close-fill "></i> Cancel</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Pas de participants </p>
    {% endif %}

    

</section>


    <script>
        $(document).ready(function() {
    
            $('.delete-trigger2').click(function() {
                event.preventDefault();
                $('.delete-container2').slideToggle();
            });
        
            $('.close-confirmation-btn2').click(function() {
                $('.delete-container2').slideToggle();
            });
        });
    </script>

    
{% endblock %}

templates/dashboard/showWorkshop.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block meta %}{% endblock %}

{% block body %}


<section id="dashboard-show">

    <div id="link-goBack" >
        <p><a href="{{ path('list_workshops') }}">Go back to all Workshops</a> <p>
    </div>

    <h1 class="text-n1">{{workshop.name}}<span>_</span></h1>
        <div id="info">
            <p>Status : 
                <span class="status {{ workshop.status == 'OPEN' ? 'open' : 
                                    (workshop.status == 'CLOSED' ? 'closed' : 
                                    (workshop.status == 'PENDING' ? 'pending' : 
                                    (workshop.status == 'ARCHIVED' ? 'archived' : 'status-default'))) }}">
                    {{ workshop.status }}
                </span>
            </p>
            <p>Date :  {{workshop.startDate|formatDate}} - {{workshop.startDate|date('H:i')}} </p>
            <p>Capacity : {{workshop.nbRegistrationMade}}  /  {{workshop.nbRooms}} - Remaining : {{workshop.nbRegistrationRemaining}} </p>

            <div class="text">
                <p>Description : </p>
                <p>{{workshop.description}}</p>
            </div>
            <div class="text">
                <p>Detail : </p>
                <p>{{workshop.detail}}</p>
            </div>
            
            <p>Quote : {{workshop.quote}}</p>

            <div id="actions">
                <a href="{{ path('edit_workshop', {slug : workshop.slug}) }}"><i class="fa-solid fa-pen-to-square"></i>edit</a>
                <a href="#"><i class="fa-regular fa-circle-xmark delete-trigger2"></i>delete</a>
            </div>
            
            <div class="delete-container2" style="display:none">
                <p>Are you sure you want to delete this entry? This cannot be undone.</p>
                <div>
                    <p><a href="{{ path('delete_workshop', {slug : workshop.slug}) }}"><i class="ri-check-line"></i> Confirm</a></p>
                    <p class="close-confirmation-btn2"><i class="ri-close-fill "></i> Cancel</p>
                </div>
            </div>

            <h2 class="text-n2">Program<span>_</span></h2>

            <div id="modules">
                
                <ul>
                    {% for module in workshop.programmes %}
                        <li>
                            <p>{{module.lesson.name}} -  
                                {{module.startDate|formatDate}} - {{module.startDate|date('H:i')}}
                                {{module.startDate|formatDate}} - {{module.startDate|date('H:i')}}
                            </p>
                        </li>
                    {% endfor %}
                </ul>
            </div>

        </div>

        <h2 class="text-n2" >Participants list<span>_</span></h2>
            
        <div id="participants">
            <ul>
                {% for participant in workshop.workshopRegistrations %}
                    <li>
                        <p>
                            {{ participant.firstname}} - {{ participant.lastname}} -  {{ participant.registrationDate|formatDate}} 
                            <a href="#"><i class="ri-close-circle-fill delete-btn" data-target="{{ participant.id}}"></i></a>
                        </p>
                        
                        <div class="delete-container" id="{{participant.id}}" style="display:none">
                            <p>Are you sure you want to delete this participation? This cannot be undone.</p>
                            <div>
                                <p><a href="{{ path('delete_registration', {'id': participant.id }) }}"><i class="ri-check-line"></i> Confirm</a></p>
                                <p class="close-confirmation-btn"><i class="ri-close-fill "></i> Cancel</p>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>



</section>

<script>
    $(document).ready(function() {

        $('.delete-trigger2').click(function() {
            event.preventDefault();
            $('.delete-container2').slideToggle();
        });
    
        $('.close-confirmation-btn2').click(function() {
            $('.delete-container2').slideToggle();
        });
    });
</script>

{% endblock %}